# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: California Building Standards Code # Your awesome title
email: webmaster@mycalcode.com # your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coding the Code
# Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
name: mycalcode.com
url: "http://mycalcode.com" # the base hostname & protocol for your site
# twitter_username:
# github_username: abrightguy

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# Exculsions
exclude: ["_posts"]

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: "codes/2013"
      type: pages
    values:
      year: (2013)
      edition: current
      layout: chapter
  -
    scope:
      path: "codes/2013/1"
      type: pages
    values:
      partname: Part 1
      partfile: part01.pdf
      description: Administrative Code
  -
    scope:
      path: "codes/2013/2"
    values:
      partname: Part 2
      partfile: part02.pdf
      description: Building Code
      layout: volumechapter
  -
    scope:
      path: "codes/2013/2/1"
    values:
      volume: Volume 1
  -
    scope:
      path: "codes/2013/2/2"
    values:
      volume: Volume 2
  -
    scope:
      path: "codes/2013/2.5"
    values:
      partname: Part 2.5
      partfile: part025.pdf
      description: Residential Code
  -
    scope:
      path: "codes/2013/3"
    values:
      partname: Part 3
      partfile: part03.pdf
      description: Electrical Code
  -
    scope:
      path: "codes/2013/4"
    values:
      partname: Part 4
      partfile: part04.pdf
      description: Mechanical Code
  -
    scope:
      path: "codes/2013/5"
    values:
      partname: Part 5
      partfile: part05.pdf
      description: Plumbing Code
  -
    scope:
      path: "codes/2013/6"
    values:
      partname: Part 6
      partfile: part06.pdf
      description: Energy Code
  -
    scope:
      path: "codes/2013/8"
    values:
      partname: Part 8
      partfile: part08.pdf
      description: Historic Building Code
  -
    scope:
      path: "codes/2013/9"
    values:
      partname: Part 9
      partfile: part09.pdf
      description: Fire Code
  -
    scope:
      path: "codes/2013/10"
    values:
      partname: Part 10
      partfile: part10.pdf
      description: Existing Building Code
  -
    scope:
      path: "codes/2013/11"
    values:
      partname: Part 11
      partfile: part11.pdf
      description: Green Building Standards Code
  -
    scope:
      path: "codes/2013/12"
    values:
      partname: Part 12
      partfile: part12.pdf
      description: Referenced Standards Code
